name: Remove historical runners

on:
  push:
    branches:
      - remove-runners

jobs:
  remove-runners:
    name: Remove historical runners
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Github runners remove
        uses: matheusrosmaninho/github-remove-old-runners@1.0.2
        with:
          api_token: "${{ secrets.WORKFLOW_ACTIONS_REMOVE }}"
          repo_owner: "matheusrosmaninho"
          repo_name: "github-actions-playground"
          days_retention: 0
