name: Share build docker betewen jobs

on:
  push:
    branches:
      - share-build-docker

jobs:
  build:
    name: Build image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.hello
          tags: hello:latest
          outputs: type=docker,dest=/tmp/hello.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello
          path: /tmp/hello.tar

  run_image:
    name: Run image
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: hello
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/hello.tar
          docker image ls -a