name: Registry upload

on:
  push:
    branches:
      - up-github-registry

jobs:
  upload_registry:
    name: Upload to registry
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_SECRET }}

      - name: Build the image
        run: |
          docker build -f Dockerfile.hello \
          -t ghcr.io/oobattousai/hello:latest .

      - name: Push
        run: |
          docker push ghcr.io/oobattousai/hello:latest

      - name: Print the actor
        run: echo ${{ github.actor }}